In [68]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
ohe = OneHotEncoder()

In [69]:
df = pd.read_csv("datasets/one_hot.csv")
df.head()

  name     sex degree  experience  salary
0  aaa  female     ug           2   10000
1  bbb    male     pg           3  200000
2  ccc    male     ug           4   10000
3  ddd  female     pg           5   10000
4  eee    male     ug           3   20000

In [27]:
df.isnull().sum()

name          0
sex           0
degree        0
experience    0
salary        0
dtype: int64

In [28]:
df.shape

(5, 5)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      object
 1   sex         5 non-null      object
 2   degree      5 non-null      object
 3   experience  5 non-null      int64
 4   salary      5 non-null      int64
dtypes: int64(2), object(3)
memory usage: 328.0+ bytes

In [30]:
df.drop(columns=['name'],inplace=True) # Makes the change directly to df without needing to reassign it.

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sex         5 non-null      object
 1   degree      5 non-null      object
 2   experience  5 non-null      int64
 3   salary      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes

In [32]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
d = df.select_dtypes(include=['object'])
d

      sex degree
0  female     ug
1    male     pg
2    male     ug
3  female     pg
4    male     ug

In [33]:
encode = ohe.fit_transform(d)
print(encode)
encoded_labels = ohe.fit_transform(d).toarray()
print(encoded_labels)

  (0, 0)	1.0
  (0, 3)	1.0
  (1, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (2, 3)	1.0
  (3, 0)	1.0
  (3, 2)	1.0
  (4, 1)	1.0
  (4, 3)	1.0
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]

In [34]:
df_encoded = pd.DataFrame(encoded_labels)
df_encoded

     0    1    2    3
0  1.0  0.0  0.0  1.0
1  0.0  1.0  1.0  0.0
2  0.0  1.0  0.0  1.0
3  1.0  0.0  1.0  0.0
4  0.0  1.0  0.0  1.0

In [35]:
df.drop(columns=d.columns,inplace=True)
df

   experience  salary
0           2   10000
1           3  200000
2           4   10000
3           5   10000
4           3   20000

In [36]:
df1 = pd.concat([df_encoded,df],ignore_index=True, axis=1)
# ignore_index parameter is used with functions like concat and append.
# It helps to control how the index of the resulting dataframe should be.
# while it is true, a new sequence of integers get generated from 0
# axis = 1 -> to specify the direction of the operation. 1 represents columns
df1

     0    1    2    3  4       5
0  1.0  0.0  0.0  1.0  2   10000
1  0.0  1.0  1.0  0.0  3  200000
2  0.0  1.0  0.0  1.0  4   10000
3  1.0  0.0  1.0  0.0  5   10000
4  0.0  1.0  0.0  1.0  3   20000

In [37]:
df1.shape

(5, 6)

In [38]:
X = df1.iloc[:,:-1]
y = df1.iloc[:,-1]
print(X)
print(y)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1, random_state=42)

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

     0    1    2    3  4
0  1.0  0.0  0.0  1.0  2
1  0.0  1.0  1.0  0.0  3
2  0.0  1.0  0.0  1.0  4
3  1.0  0.0  1.0  0.0  5
4  0.0  1.0  0.0  1.0  3
0     10000
1    200000
2     10000
3     10000
4     20000
Name: 5, dtype: int64

LinearRegression()

In [39]:
lm.coef_

array([-10000.,  10000.,  15000., -15000., -10000.])

In [40]:
lm.intercept_

54999.99999999996

### exe with own dataset

In [70]:
df = pd.read_csv("datasets/diamonds.csv")
df.head()

   carat      cut color clarity  depth  table     x     y     z  price
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335

In [42]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
x          0
y          0
z          0
price      0
dtype: int64

In [43]:
df.shape

(53940, 10)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   x        53940 non-null  float64
 7   y        53940 non-null  float64
 8   z        53940 non-null  float64
 9   price    53940 non-null  int64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [66]:
# Assuming df is your dataframe
correlations = df1.corr()

# Correlation of all features with price
price_corr = correlations[20].sort_values(ascending=False)
print(price_corr)

20    1.000000
13    0.921591
17    0.884435
18    0.865421
19    0.861249
8     0.128420
3     0.095706
0     0.018728
7     0.008957
4     0.006593
5    -0.000255
1    -0.000312
10   -0.001062
9    -0.009886
6    -0.049596
12   -0.052381
11   -0.095266
2    -0.097175
Name: 20, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_12792\1093563993.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlations = df1.corr()

In [67]:
df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,15,17,18,19,20
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.23,E,3.95,3.98,2.43,326
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.21,E,3.89,3.84,2.31,326
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.23,E,4.05,4.07,2.31,327
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.29,I,4.20,4.23,2.63,334
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.31,J,4.34,4.35,2.75,335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.72,D,5.75,5.76,3.50,2757
53936,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.72,D,5.69,5.75,3.61,2757
53937,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.70,D,5.66,5.68,3.56,2757
53938,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.86,H,6.15,6.12,3.74,2757
53939,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.75,D,5.83,5.87,3.64,2757

In [46]:
df = df.drop(['table', 'depth'], axis=1)

In [47]:
df[['cut','clarity']]

             cut clarity
0          Ideal     SI2
1        Premium     SI1
2           Good     VS1
3        Premium     VS2
4           Good     SI2
...          ...     ...
53935      Ideal     SI1
53936       Good     SI1
53937  Very Good     SI1
53938    Premium     SI2
53939      Ideal     SI2

[53940 rows x 2 columns]

In [48]:
encode = ohe.fit_transform(df[['cut','clarity']])
encode

<53940x13 sparse matrix of type '<class 'numpy.float64'>'
	with 107880 stored elements in Compressed Sparse Row format>

In [49]:
encoded_lables = ohe.fit_transform(df[['cut','clarity']]).toarray()
encoded_lables

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [50]:
df_encoded = pd.DataFrame(encoded_lables)
df_encoded

        0    1    2    3    4    5    6    7    8    9    10   11   12
0      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
3      0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
53935  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
53936  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
53937  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
53938  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
53939  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[53940 rows x 13 columns]

In [51]:
df_encoded[2].unique()

array([1., 0.])

In [52]:
df['clarity'].unique()

array(['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF'],
      dtype=object)

In [53]:
df['cut'].unique()

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)

In [54]:
df1 = pd.concat([df_encoded,df],ignore_index=True, axis=1)
df1

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.23,Ideal,E,SI2,3.95,3.98,2.43,326
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.21,Premium,E,SI1,3.89,3.84,2.31,326
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.23,Good,E,VS1,4.05,4.07,2.31,327
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.29,Premium,I,VS2,4.20,4.23,2.63,334
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.31,Good,J,SI2,4.34,4.35,2.75,335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.72,Ideal,D,SI1,5.75,5.76,3.50,2757
53936,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.72,Good,D,SI1,5.69,5.75,3.61,2757
53937,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.70,Very Good,D,SI1,5.66,5.68,3.56,2757
53938,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.86,Premium,H,SI2,6.15,6.12,3.74,2757
53939,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.75,Ideal,D,SI2,5.83,5.87,3.64,2757

In [62]:
df1 = df1.drop(df1.columns[[14, 16]], axis=1)

In [63]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,15,17,18,19,20
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.23,E,3.95,3.98,2.43,326
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.21,E,3.89,3.84,2.31,326
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.23,E,4.05,4.07,2.31,327
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.29,I,4.20,4.23,2.63,334
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.31,J,4.34,4.35,2.75,335

In [71]:
from pandas.api.types import CategoricalDtype

# Define ordered categories
cut_order = CategoricalDtype(categories=['Fair', 'Good', 'Very Good', 'Premium', 'Ideal'], ordered=True)
clarity_order = CategoricalDtype(categories=['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF'], ordered=True)

# Apply to DataFrame
df['cut'] = df['cut'].astype(cut_order)
df['clarity'] = df['clarity'].astype(clarity_order)

# Now one-hot encode
df_encoded = pd.get_dummies(df, columns=['cut', 'clarity'], prefix=['cut', 'clarity'])

In [72]:
df_encoded

,carat,color,depth,table,x,y,z,price,cut_Fair,cut_Good,...,cut_Premium,cut_Ideal,clarity_I1,clarity_SI2,clarity_SI1,clarity_VS2,clarity_VS1,clarity_VVS2,clarity_VVS1,clarity_IF
0,0.23,E,61.5,55.0,3.95,3.98,2.43,326,0,0,...,0,1,0,1,0,0,0,0,0,0
1,0.21,E,59.8,61.0,3.89,3.84,2.31,326,0,0,...,1,0,0,0,1,0,0,0,0,0
2,0.23,E,56.9,65.0,4.05,4.07,2.31,327,0,1,...,0,0,0,0,0,0,1,0,0,0
3,0.29,I,62.4,58.0,4.20,4.23,2.63,334,0,0,...,1,0,0,0,0,1,0,0,0,0
4,0.31,J,63.3,58.0,4.34,4.35,2.75,335,0,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,D,60.8,57.0,5.75,5.76,3.50,2757,0,0,...,0,1,0,0,1,0,0,0,0,0
53936,0.72,D,63.1,55.0,5.69,5.75,3.61,2757,0,1,...,0,0,0,0,1,0,0,0,0,0
53937,0.70,D,62.8,60.0,5.66,5.68,3.56,2757,0,0,...,0,0,0,0,1,0,0,0,0,0
53938,0.86,H,61.0,58.0,6.15,6.12,3.74,2757,0,0,...,1,0,0,1,0,0,0,0,0,0
53939,0.75,D,62.2,55.0,5.83,5.87,3.64,2757,0,0,...,0,1,0,1,0,0,0,0,0,0

In [76]:
cor = df_encoded.corr()
# Correlation of all features with price
price_corr = cor['price'].sort_values(ascending=False)
print(price_corr)

price            1.000000
carat            0.921591
x                0.884435
y                0.865421
z                0.861249
clarity_SI2      0.128420
table            0.127134
cut_Premium      0.095706
cut_Fair         0.018728
clarity_SI1      0.008957
cut_Very Good    0.006593
clarity_I1      -0.000255
cut_Good        -0.000312
clarity_VS2     -0.001062
clarity_VS1     -0.009886
depth           -0.010647
clarity_IF      -0.049596
clarity_VVS2    -0.052381
clarity_VVS1    -0.095266
cut_Ideal       -0.097175
Name: price, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_12792\866414325.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  cor = df_encoded.corr()

In [79]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np
# 1. Separate features and target
X = df_encoded.drop(['price','color'], axis=1)
y = df_encoded['price']

# 2. Split into train/test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize and train model
model = LinearRegression()
model.fit(X_train, y_train)

# 4. Make predictions
y_pred = model.predict(X_test)

# 5. Evaluate the model
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.2f}")

R² Score: 0.8993
RMSE: 1265.48