In [1]:
import pandas as pd
df = pd.read_csv("datasets/one_hot.csv")
df.head()

  name     sex degree  experience  salary
0  aaa  female     ug           2   10000
1  bbb    male     pg           3  200000
2  ccc    male     ug           4   10000
3  ddd  female     pg           5   10000
4  eee    male     ug           3   20000

In [2]:
df.isnull().sum()

name          0
sex           0
degree        0
experience    0
salary        0
dtype: int64

In [3]:
df.shape

(5, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      object
 1   sex         5 non-null      object
 2   degree      5 non-null      object
 3   experience  5 non-null      int64
 4   salary      5 non-null      int64
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

In [5]:
df.drop(columns=['name'],inplace=True) # Makes the change directly to df without needing to reassign it.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   sex         5 non-null      object
 1   degree      5 non-null      object
 2   experience  5 non-null      int64
 3   salary      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [7]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
d = df.select_dtypes(include=['object'])
d

      sex degree
0  female     ug
1    male     pg
2    male     ug
3  female     pg
4    male     ug

In [ ]:
# d.info()
# # Assuming df is your dataframe
# correlations = df1.corr()

# # Correlation of all features with price
# price_corr = correlations[20].sort_values(ascending=False)
# print(price_corr)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sex     5 non-null      object
 1   degree  5 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

NameError: name 'df1' is not defined

In [9]:
encode = ohe.fit_transform(d)
print(encode)
encoded_labels = ohe.fit_transform(d).toarray()
print(encoded_labels)

  (0, 0)	1.0
  (0, 3)	1.0
  (1, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (2, 3)	1.0
  (3, 0)	1.0
  (3, 2)	1.0
  (4, 1)	1.0
  (4, 3)	1.0
[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]

In [ ]:
# df = df.drop(['table', 'depth'], axis=1)

KeyError: "['table', 'depth'] not found in axis"

In [ ]:
df[['cut','clarity']]

             cut clarity
0          Ideal     SI2
1        Premium     SI1
2           Good     VS1
3        Premium     VS2
4           Good     SI2
...          ...     ...
53935      Ideal     SI1
53936       Good     SI1
53937  Very Good     SI1
53938    Premium     SI2
53939      Ideal     SI2

[53940 rows x 2 columns]

In [ ]:
encode = ohe.fit_transform(df[['cut','clarity']])
encode

<53940x13 sparse matrix of type '<class 'numpy.float64'>'
	with 107880 stored elements in Compressed Sparse Row format>

In [ ]:
encoded_lables = ohe.fit_transform(df[['cut','clarity']]).toarray()
encoded_lables

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [ ]:
df1 = pd.concat([df_encoded,df],ignore_index=True, axis=1)
df1

     0    1    2    3  4       5
0  1.0  0.0  0.0  1.0  2   10000
1  0.0  1.0  1.0  0.0  3  200000
2  0.0  1.0  0.0  1.0  4   10000
3  1.0  0.0  1.0  0.0  5   10000
4  0.0  1.0  0.0  1.0  3   20000

In [ ]:
df1.shape

(5, 6)

In [ ]:
X = df1.iloc[:,:-1]
y = df1.iloc[:,-1]
print(X)
print(y)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1, random_state=42)

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

     0    1    2    3  4
0  1.0  0.0  0.0  1.0  2
1  0.0  1.0  1.0  0.0  3
2  0.0  1.0  0.0  1.0  4
3  1.0  0.0  1.0  0.0  5
4  0.0  1.0  0.0  1.0  3
0     10000
1    200000
2     10000
3     10000
4     20000
Name: 5, dtype: int64

LinearRegression()

In [ ]:
lm.coef_

array([-10000.,  10000.,  15000., -15000., -10000.])

In [ ]:
lm.intercept_

54999.999999999985

## With Own dataset

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
df = pd.read_csv("datasets/car.csv")
df.head()

  Car Model  Mileage  Sell Price  Age
0      Audi    87000       76543    2
1      Audi    67000       58760    3
2      Audi    45000       27650    4
3    BMW X5    78000       66540    7
4    BMW X5    67000       56450    1

In [13]:
df.shape

(22, 4)

In [14]:
df.isnull().sum()

Car Model     0
Mileage       0
Sell Price    0
Age           0
dtype: int64

In [15]:
x = df.drop(["Sell Price"], axis = 1)
y = df['Sell Price']

In [16]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [17]:
encoded_labels = ohe.fit_transform(df[['Car Model']]).toarray()
print(encoded_labels)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]

In [18]:
dum = pd.DataFrame(encoded_labels)

In [ ]:
# dum = pd.get_dummies(x["Car Model"])
# dum.head()

In [19]:
combained = pd.concat([x,dum], axis = 1)
combained.head()

  Car Model  Mileage  Age    0    1    2    3
0      Audi    87000    2  1.0  0.0  0.0  0.0
1      Audi    67000    3  1.0  0.0  0.0  0.0
2      Audi    45000    4  1.0  0.0  0.0  0.0
3    BMW X5    78000    7  0.0  1.0  0.0  0.0
4    BMW X5    67000    1  0.0  1.0  0.0  0.0

In [21]:
final_df = combained.drop(["Car Model","Age"], axis = "columns")
final_df

    Mileage    0    1    2    3
0     87000  1.0  0.0  0.0  0.0
1     67000  1.0  0.0  0.0  0.0
2     45000  1.0  0.0  0.0  0.0
3     78000  0.0  1.0  0.0  0.0
4     67000  0.0  1.0  0.0  0.0
5     87500  0.0  0.0  0.0  1.0
6     87000  0.0  1.0  0.0  0.0
7     47600  0.0  1.0  0.0  0.0
8     87650  0.0  1.0  0.0  0.0
9     78650  1.0  0.0  0.0  0.0
10    89760  1.0  0.0  0.0  0.0
11    23000  1.0  0.0  0.0  0.0
12    43500  1.0  0.0  0.0  0.0
13    65900  0.0  0.0  1.0  0.0
14    76000  0.0  0.0  1.0  0.0
15    76500  0.0  0.0  1.0  0.0
16    76500  0.0  0.0  1.0  0.0
17    87650  0.0  0.0  1.0  0.0
18    76230  0.0  0.0  0.0  1.0
19    65470  0.0  0.0  0.0  1.0
20    65430  0.0  0.0  0.0  1.0
21    98600  0.0  0.0  0.0  1.0

In [ ]:
from sklearn.preprocessing import train_test_split

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()