In [21]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
ohe = OneHotEncoder()

In [3]:
df = pd.read_csv("datasets/diamonds.csv")
df.head()

   carat      cut color clarity  depth  table     x     y     z  price
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335

In [9]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
x          0
y          0
z          0
price      0
dtype: int64

In [11]:
df.shape

(53940, 10)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   x        53940 non-null  float64
 7   y        53940 non-null  float64
 8   z        53940 non-null  float64
 9   price    53940 non-null  int64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [8]:
# Assuming df is your dataframe
correlations = df.corr()

# Correlation of all features with price
price_corr = correlations['price'].sort_values(ascending=False)
print(price_corr)

price    1.000000
carat    0.921591
x        0.884435
y        0.865421
z        0.861249
table    0.127134
depth   -0.010647
Name: price, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_5004\1134818772.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlations = df.corr()

In [42]:
encode = ohe.fit_transform(df['cut'])
encode

ValueError: Expected 2D array, got 1D array instead:
array=['Ideal' 'Premium' 'Good' ... 'Very Good' 'Premium' 'Ideal'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [41]:
encoded_lables = ohe.fit_transform(df['cut']).toarray()
encoded_lables

ValueError: Expected 2D array, got 1D array instead:
array=['Ideal' 'Premium' 'Good' ... 'Very Good' 'Premium' 'Ideal'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [26]:
df_encoded = pd.DataFrame(encoded_lables)
df_encoded

        0    1    2    3    4    5    6    7    8    9    10   11   12
0      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
3      0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
53935  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
53936  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
53937  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
53938  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
53939  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[53940 rows x 13 columns]

In [40]:
df_encoded[2].unique()

array([1., 0.])

In [31]:
df['clarity'].unique()

array(['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF'],
      dtype=object)

In [36]:
df['cut'].unique()

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)

In [32]:
cut_categories = ['Premium', 'Good', 'Very Good', 'Fair']
clarity_categories = ['SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']

# Create combined column names
encoded_col_names = [f'cut_{cat}' for cat in cut_categories] + [f'clarity_{cat}' for cat in clarity_categories]

print(encoded_col_names)

['cut_Premium', 'cut_Good', 'cut_Very Good', 'cut_Fair', 'clarity_SI1', 'clarity_VS1', 'clarity_VS2', 'clarity_VVS2', 'clarity_VVS1', 'clarity_I1', 'clarity_IF']

In [35]:
encoded_df = pd.DataFrame(df_encoded, columns=encoded_col_names)

print(df_encoded.head())

    0    1    2    3    4    5    6    7    8    9    10   11   12
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
4  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0