In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder as ohe

In [2]:
df = pd.read_csv("one_hot.csv")
df

  name     sex degree  experience  salary
0  aaa  female     ug           2   10000
1  bbb    male     pg           3  200000
2  ccc    male     ug           4   10000
3  ddd  female     pg           5   10000
4  eee    male     ug           3   20000

In [3]:
df.isnull().sum()

name          0
sex           0
degree        0
experience    0
salary        0
dtype: int64

In [4]:
df.shape

(5, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      object
 1   sex         5 non-null      object
 2   degree      5 non-null      object
 3   experience  5 non-null      int64
 4   salary      5 non-null      int64
dtypes: int64(2), object(3)
memory usage: 328.0+ bytes

In [6]:
df.drop(columns=['name'],inplace=True)
df.sample

<bound method NDFrame.sample of       sex degree  experience  salary
0  female     ug           2   10000
1    male     pg           3  200000
2    male     ug           4   10000
3  female     pg           5   10000
4    male     ug           3   20000>

In [9]:
d = df.select_dtypes(include=['object'])
d

      sex degree
0  female     ug
1    male     pg
2    male     ug
3  female     pg
4    male     ug

In [ ]:
encode = ohe.fit_transform(d)
print(encode)
encoded_labels = ohe.fit_transform(d).toarray()
print(encoded_labels)

TypeError: TransformerMixin.fit_transform() missing 1 required positional argument: 'X'